// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeT4ageCQOQh68FZOibvZYfWY5tLyNJx0',
    appId: '1:131551045783:web:b58d6695f17ba5f452a1d2',
    messagingSenderId: '131551045783',
    projectId: 'student-performance-trac-48d78',
    authDomain: 'student-performance-trac-48d78.firebaseapp.com',
    storageBucket: 'student-performance-trac-48d78.appspot.com',
    measurementId: 'G-VY1TW9ENE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWlIOPMWPNeq5FjPaLDbI3HtFhKX2u_Ng',
    appId: '1:131551045783:android:c83e7f811b5e5e2052a1d2',
    messagingSenderId: '131551045783',
    projectId: 'student-performance-trac-48d78',
    storageBucket: 'student-performance-trac-48d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjdEZa6Ls6mz-9saL_ZG26RRXVuedE6JY',
    appId: '1:131551045783:ios:e4e8f5ce7dd56c0252a1d2',
    messagingSenderId: '131551045783',
    projectId: 'student-performance-trac-48d78',
    storageBucket: 'student-performance-trac-48d78.appspot.com',
    iosBundleId: 'com.example.userFormApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjdEZa6Ls6mz-9saL_ZG26RRXVuedE6JY',
    appId: '1:131551045783:ios:e4e8f5ce7dd56c0252a1d2',
    messagingSenderId: '131551045783',
    projectId: 'student-performance-trac-48d78',
    storageBucket: 'student-performance-trac-48d78.appspot.com',
    iosBundleId: 'com.example.userFormApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeT4ageCQOQh68FZOibvZYfWY5tLyNJx0',
    appId: '1:131551045783:web:e8f28b15f5064f2052a1d2',
    messagingSenderId: '131551045783',
    projectId: 'student-performance-trac-48d78',
    authDomain: 'student-performance-trac-48d78.firebaseapp.com',
    storageBucket: 'student-performance-trac-48d78.appspot.com',
    measurementId: 'G-6CWN6Q8TER',
  );
}
